notification:
  device-token-cutoff-days: 30
  notification-cutoff-days: 7

plan:
  task-cutoff-days: 30

team:
  invitation-cutoff-days: 7
  max-owned-teams: 3

chatbot:
  daily-quota-tokens: 15000
  avg-tokens-per-request: 500
  char-per-token: 3
  max-file-size: 10MB
  max-total-size: 20MB

file:
  user-usage-limit: 2147483648
  team-usage-limit: 3221225472
  max-size: 200MB
  file-cutoff-days: 30

session:
  default-focus-time-in-seconds: 2700
  default-break-time-in-seconds: 900
  default-total-time-in-seconds: 3600
  default-enable-bg-music: false

chat:
  max-file-size: 10MB
  max-total-size: 20MB
  edit-time-limit-seconds: 6000