quartz:
  job-packages: com.study.studypal.team.job, com.study.studypal.notification.job
  jobs:
    invitation-clean-up: "0 0 0 * * ?"
    device-token-clean-up: " 0 0 0 * * ?"
    notification-clean-up: "0 0 0 * * ?"
    task-clean-up: "0 0 0 * * ?"