quartz:
  job-packages: com.study.studypal.team.job, com.study.studypal.notification.job,
    com.study.studypal.plan.job, com.study.studypal.chatbot.job, com.study.studypal.file.job,
    com.study.studypal.chat.job, com.study.studypal.session.job
  jobs:
    invitation-clean-up: "0 0 0 * * ?"
    device-token-clean-up: " 0 0 0 * * ?"
    notification-clean-up: "0 0 0 * * ?"
    task-clean-up: "0 0 0 * * ?"
    reset-daily-quota: "0 0 0 * * ?"
    file-clean-up: "0 0 0 * * ?"
    message-clean-up: "0 0 0 * * ?"
    chatbot-message-clean-up: "0 0 0 * * ?"
    session-clean-up: "0 0 0 * * ?"